name: Build Minadmap

on:
  push:
    branches: [main]
    paths:
      - "md/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - uses: actions/checkout@v4

      - name: Install dependency
        run: npm install markmap-cli@0.13.2

      - name: Run convert script
        run: bash md2mindmap.sh

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global --add safe.directory /__w/mindmap/mindmap
          git add .
          git commit -m "Automated changes" || exit 0
          git push
